#!/usr/bin/env python3
"""Phase 0: write ComicInfo.xml into every CBZ in the library, in place.

    python3 tools/phase0_comicinfo.py ROOT [--dry] [--limit N] [--force]

Per archive: read every image header for dimensions, build ComicInfo.xml,
rebuild to a temp file in the exact original entry order preserving each
entry's compression method, renaming image entries to a zero-padded
sequence (0000.jpg, 0001.jpg, ...) so filename sort == reading order in
every reader, verify (count, per-position CRCs/sizes/methods, testzip,
XML parses, sorted names == entry order), then atomically replace.
Aborts the archive on any mismatch. Entry order is the truth: 15 archives
had covers/colour pages that a name sort scrambled (2026-09-07).
Never touches an archive that already has ComicInfo.xml unless --force.
"""
import io, os, re, sys, time, zipfile, datetime, unicodedata
from xml.sax.saxutils import escape
import tempfile
from PIL import Image

IMG = (".jpg", ".jpeg", ".png", ".webp", ".gif")
FW2ASCII = str.maketrans("０１２３４５６７８９", "0123456789")
VOL_RE = re.compile(r"^(?P<series>.*?)\s*(?P<num>[０-９0-9]+)(?P<sfx>[a-z]?)$")

def nat_key(s):
    return [(0, int(p)) if p.isdigit() else (1, p) for p in re.split(r"(\d+)", s)]

def parse_name(stem, folder):
    m = VOL_RE.match(stem)
    if not m:
        return unicodedata.normalize("NFC", folder), "", unicodedata.normalize("NFC", stem)  # 外伝: no Number
    series = unicodedata.normalize("NFC", m.group("series").strip() or folder)
    num = m.group("num").translate(FW2ASCII).lstrip("0") or "0"
    return series, num + m.group("sfx"), unicodedata.normalize("NFC", stem)

def build_xml(series, number, title, pages, page_dims):
    volume = re.sub(r"\D", "", number)
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">',
             f"  <Title>{escape(title)}</Title>",
             f"  <Series>{escape(series)}</Series>"]
    if number: lines.append(f"  <Number>{escape(number)}</Number>")
    if volume: lines.append(f"  <Volume>{int(volume)}</Volume>")
    else: lines.append("  <Format>Special</Format>")
    lines += ["  <LanguageISO>ja</LanguageISO>",
              "  <Manga>YesAndRightToLeft</Manga>",
              f"  <PageCount>{len(pages)}</PageCount>",
              f"  <Notes>ComicInfo generated by kanpeki phase0 on {datetime.date.today().isoformat()}</Notes>",
              "  <Pages>"]
    for i, name in enumerate(pages):
        w, h, size = page_dims[name]
        attrs = f'Image="{i}"'
        if i == 0: attrs += ' Type="FrontCover"'
        if w > h: attrs += ' DoublePage="true"'
        attrs += f' ImageSize="{size}" ImageWidth="{w}" ImageHeight="{h}"'
        lines.append(f"    <Page {attrs} />")
    lines += ["  </Pages>", "</ComicInfo>", ""]
    return "\n".join(lines)

def process(path, dry, force, log):
    rel = os.path.relpath(path, ROOT)
    if os.path.basename(path).startswith("."):
        return "skip-hidden"
    zin = zipfile.ZipFile(path)
    infos = zin.infolist()
    names = [i.filename for i in infos]
    if "ComicInfo.xml" in names and not force:
        zin.close(); return "has-comicinfo"
    images = [n for n in names if n.lower().endswith(IMG) and not n.startswith("__MACOSX") and not os.path.basename(n).startswith(".")]
    if not images:
        zin.close(); return "ABORT no images"
    ordered = images                      # entry order IS the reading order
    if sorted(images, key=nat_key) != images:
        log(f"  note: name sort disagreed with entry order; renaming fixes it: {rel}")
    newname = {n: f"{i:04d}{os.path.splitext(n)[1].lower()}" for i, n in enumerate(ordered)}
    dims = {}
    for n in ordered:
        info = zin.getinfo(n)
        with zin.open(n) as f:
            try:
                im = Image.open(f); w, h = im.size
            except Exception as e:
                zin.close(); return f"ABORT unreadable image {n}: {e}"
        dims[n] = (w, h, info.file_size)
    folder = os.path.basename(os.path.dirname(path))
    stem = os.path.splitext(os.path.basename(path))[0]
    series, number, title = parse_name(stem, folder)
    xml = build_xml(series, number, title, ordered, dims)
    wide = sum(1 for n in ordered if dims[n][0] > dims[n][1])
    msg = f"series={series} number={number or '-'} pages={len(ordered)} wide={wide}"
    if dry:
        zin.close(); return msg + " (dry)"
    # Temp lives outside the iCloud folder (same APFS volume, so os.replace is an atomic rename).
    tmp = os.path.join(TMPDIR, os.path.basename(path) + ".phase0.tmp")
    kept = [i for i in infos if i.filename != "ComicInfo.xml"]
    orig = [(i.CRC, i.file_size, i.compress_type) for i in kept]
    with zipfile.ZipFile(tmp, "w") as zout:
        for i in kept:  # exact original order, per-entry method preserved, image names sequential
            zi = zipfile.ZipInfo(newname.get(i.filename, i.filename), date_time=i.date_time)
            zi.compress_type = i.compress_type
            zi.external_attr = i.external_attr
            zi.flag_bits = i.flag_bits & 0x800
            zout.writestr(zi, zin.read(i.filename))
        ci = zipfile.ZipInfo("ComicInfo.xml", date_time=time.localtime()[:6])
        ci.compress_type = zipfile.ZIP_STORED
        ci.external_attr = 0o644 << 16
        zout.writestr(ci, xml.encode("utf-8"))
    zin.close()
    # verify
    try:
        zc = zipfile.ZipFile(tmp)
        new = zc.infolist()
        expect = [newname.get(i.filename, i.filename) for i in kept] + ["ComicInfo.xml"]
        if [i.filename for i in new] != expect:
            raise RuntimeError("order mismatch")
        for i, (crc, size, method) in zip(new[:-1], orig):
            if i.CRC != crc or i.file_size != size or i.compress_type != method:
                raise RuntimeError(f"entry mismatch at {i.filename}")
        imgs = [i.filename for i in new if i.filename.lower().endswith(IMG)]
        if sorted(imgs, key=nat_key) != imgs:
            raise RuntimeError("renamed entries do not sort in entry order")
        if zc.testzip() is not None:
            raise RuntimeError("testzip failed")
        import xml.etree.ElementTree as ET
        ET.fromstring(zc.read("ComicInfo.xml"))
        zc.close()
    except Exception as e:
        os.remove(tmp); return f"ABORT verify: {e}"
    os.replace(tmp, path)
    return msg

if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        sys.exit("usage: phase0_comicinfo.py ROOT [--dry] [--limit N] [--force]")
    ROOT = args[0]
    dry = "--dry" in sys.argv; force = "--force" in sys.argv
    limit = int(sys.argv[sys.argv.index("--limit") + 1]) if "--limit" in sys.argv else None
    report = os.path.join(os.path.dirname(os.path.abspath(__file__)), "phase0_report.log")
    TMPDIR = os.environ.get("PHASE0_TMP") or os.path.join(tempfile.gettempdir(), "phase0tmp")
    os.makedirs(TMPDIR, exist_ok=True)
    def log(m):
        print(m, flush=True)
        with open(report, "a") as f: f.write(m + "\n")
    log(f"===== phase0 {datetime.datetime.now():%Y-%m-%d %H:%M} root={ROOT} dry={dry} =====")
    files = []
    for d, _, fs in os.walk(ROOT):
        for f in fs:
            if f.endswith(".icloud"): log(f"  NOT LOCAL (iCloud placeholder): {os.path.join(d, f)}")
            if f.endswith(".cbz") and not f.startswith("."): files.append(os.path.join(d, f))
    files.sort(key=nat_key)
    if limit: files = files[:limit]
    counts = {}
    for p in files:
        r = process(p, dry, force, log)
        key = r.split()[0] if r.startswith(("ABORT", "skip", "has")) else "ok"
        counts[key] = counts.get(key, 0) + 1
        log(f"  {os.path.relpath(p, ROOT)[:44]:46} {r}")
    log(f"done: {counts} of {len(files)} files")
